lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
google_analytics: G-ZFF1LCR9YC
paypal:
  accept_donations: true
  donate_url: https://www.paypal.com/donate/?hosted_button_id=P7TX8SKF45TGU
